import { FormControl, FormGroup, Validators } from '@angular/forms';

export const taskList: Set<FormGroup> = new Set([
  new FormGroup({
    title: new FormControl('Hit the gym', [Validators.required]),
    discription: new FormControl('Trying to stay healthy for a year!'),
    importance: new FormControl(false, [Validators.required]),
    completed: new FormControl(false, [Validators.required]),
    createdOn: new FormControl(`2022-05-01`, [Validators.required]),
    deadline: new FormControl(`2023-05-01`),
    editingStatus: new FormControl(false, [Validators.required]),
  }),
  new FormGroup({
    title: new FormControl('Pay bills', [Validators.required]),
    discription: new FormControl(''),
    importance: new FormControl(true, [Validators.required]),
    completed: new FormControl(false, [Validators.required]),
    createdOn: new FormControl(`2022-08-13`, [Validators.required]),
    deadline: new FormControl('2022-08-20'),
    editingStatus: new FormControl(false, [Validators.required]),
  }),
  new FormGroup({
    title: new FormControl('Meet George', [Validators.required]),
    discription: new FormControl('business meeting with George on Friday'),
    importance: new FormControl(true, [Validators.required]),
    completed: new FormControl(false, [Validators.required]),
    createdOn: new FormControl(`2022-08-15`, [Validators.required]),
    deadline: new FormControl(`2022-08-19`),
    editingStatus: new FormControl(false, [Validators.required]),
  }),
  new FormGroup({
    title: new FormControl('Buy stuff from supermarket', [Validators.required]),
    discription: new FormControl('Eggs, Milk, etc.'),
    importance: new FormControl(true, [Validators.required]),
    completed: new FormControl(false, [Validators.required]),
    createdOn: new FormControl(`2022-08-15`, [Validators.required]),
    deadline: new FormControl(),
    editingStatus: new FormControl(false, [Validators.required]),
  }),
  new FormGroup({
    title: new FormControl('Read a book', [Validators.required]),
    discription: new FormControl("Harry Potter and the Philosopher's Stone"),
    importance: new FormControl(false, [Validators.required]),
    completed: new FormControl(false, [Validators.required]),
    createdOn: new FormControl(`2022-08-03`, [Validators.required]),
    deadline: new FormControl(),
    editingStatus: new FormControl(false, [Validators.required]),
  }),
  new FormGroup({
    title: new FormControl('Organize office', [Validators.required]),
    discription: new FormControl(),
    importance: new FormControl(true, [Validators.required]),
    completed: new FormControl(false, [Validators.required]),
    createdOn: new FormControl(`2022-05-12`, [Validators.required]),
    deadline: new FormControl('2022-05-19'),
    editingStatus: new FormControl(false, [Validators.required]),
  }),
  new FormGroup({
    title: new FormControl('See the Doctor', [Validators.required]),
    discription: new FormControl(),
    importance: new FormControl(true, [Validators.required]),
    completed: new FormControl(true, [Validators.required]),
    createdOn: new FormControl(`2022-07-29`, [Validators.required]),
    deadline: new FormControl(),
    editingStatus: new FormControl(false, [Validators.required]),
  }),
  new FormGroup({
    title: new FormControl('Meet friends', [Validators.required]),
    discription: new FormControl('Spend some time with firends!'),
    importance: new FormControl(false, [Validators.required]),
    completed: new FormControl(true, [Validators.required]),
    createdOn: new FormControl(`2022-07-15`, [Validators.required]),
    deadline: new FormControl('2022-07-20'),
    editingStatus: new FormControl(false, [Validators.required]),
  }),
]);
